<a href="https://colab.research.google.com/github/juma-paul/deep_learning/blob/main/Logisitc_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression Classification

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# Import necessary packages
import pandas as pd
import numpy as np

In [3]:
# Load the dataset
path_to_data = '/content/drive/MyDrive/Datasets/DataScienceCaseStudy/final_clean_data.csv'
insurance = pd.read_csv(path_to_data)

In [4]:
insurance.head()

pet_name      service  check up  dental cleaning  lab test  surgery  \
0   Sophie  vaccination       0.0              0.0      0.00      0.0   
1   Sophie  vaccination       0.0              0.0      0.00      0.0   
2   Sophie  vaccination       0.0              0.0      0.00      0.0   
3   Harper     lab test       0.0              0.0   1712.08      0.0   
4   Harper     lab test       0.0              0.0   1070.22      0.0   

   vaccination  x-ray auth_status  
0      1162.17    0.0    Approved  
1       921.42    0.0    Approved  
2      1295.25    0.0    Approved  
3         0.00    0.0    Approved  
4         0.00    0.0    Approved

In [5]:
# Extract the required columns
insurance = insurance[['service', 'check up', 'dental cleaning', 'lab test',
       'surgery', 'vaccination', 'x-ray', 'auth_status']].copy()

In [6]:
insurance.head()

service  check up  dental cleaning  lab test  surgery  vaccination  \
0  vaccination       0.0              0.0      0.00      0.0      1162.17   
1  vaccination       0.0              0.0      0.00      0.0       921.42   
2  vaccination       0.0              0.0      0.00      0.0      1295.25   
3     lab test       0.0              0.0   1712.08      0.0         0.00   
4     lab test       0.0              0.0   1070.22      0.0         0.00   

   x-ray auth_status  
0    0.0    Approved  
1    0.0    Approved  
2    0.0    Approved  
3    0.0    Approved  
4    0.0    Approved

### 1. Preprocess  and split the data into training and test setsdata

In [7]:
# Replace all Penied stauses as Denied
insurance['auth_status'] = insurance['auth_status'].replace('Pending', 'Denied')
np.unique(insurance['auth_status'])

array(['Approved', 'Denied'], dtype=object)

In [8]:
# Encode approved as 1 and Denied as 0
insurance['auth_status'] = insurance['auth_status'].replace({'Approved': 1, 'Denied': 0})
np.unique(insurance['auth_status'])

array([0, 1])

In [9]:
insurance.sample(3)

service  check up  dental cleaning  lab test  surgery  vaccination  \
433  check up    332.33              0.0       0.0     0.00          0.0   
862     x-ray      0.00              0.0       0.0     0.00          0.0   
683   surgery      0.00              0.0       0.0    29.84          0.0   

      x-ray  auth_status  
433    0.00            1  
862  177.19            0  
683    0.00            1

In [10]:
# Divide the data into features (X) and label (y)
X = insurance.drop(columns=['auth_status'])
y = insurance['auth_status']

In [11]:
X.tail()

service  check up  dental cleaning  lab test  surgery  vaccination  \
926  lab test       0.0              0.0    427.07      0.0          0.0   
927  lab test       0.0              0.0    653.31      0.0          0.0   
928  lab test       0.0              0.0   1254.74      0.0          0.0   
929  lab test       0.0              0.0    540.97      0.0          0.0   
930  lab test       0.0              0.0   1683.93      0.0          0.0   

     x-ray  
926    0.0  
927    0.0  
928    0.0  
929    0.0  
930    0.0

In [12]:
y.sample(3)

738    0
49     1
760    1
Name: auth_status, dtype: int64

In [13]:
X.dtypes

service             object
check up           float64
dental cleaning    float64
lab test           float64
surgery            float64
vaccination        float64
x-ray              float64
dtype: object

In [33]:
# Exract categorical and numerical datatypes
categorical_data = X.select_dtypes(['object']).columns
numeric_data = X.select_dtypes(['float64', 'int64']).columns

In [15]:
# Encode all categorical varialbles using one-hot encoder
X = pd.get_dummies(X, categorical_data, drop_first=True)

In [16]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
# Scale training set using standard scaler and transform test set using the same scaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train[numeric_data] = scaler.fit_transform(X_train[numeric_data])
X_test[numeric_data] = scaler.transform(X_test[numeric_data])

In [18]:
X_train

check up  dental cleaning  lab test   surgery  vaccination     x-ray  \
54  -0.423748        -0.377512 -0.235114 -0.297273    -0.330528 -0.410106   
299  3.550615        -0.377512 -0.314120 -0.297273    -0.330528 -0.410106   
501 -0.423748         1.080678 -0.314120 -0.297273    -0.330528 -0.410106   
810  1.314285        -0.377512 -0.314120 -0.297273    -0.330528 -0.410106   
394 -0.423748        -0.377512 -0.314120 -0.297273    -0.330528  2.583926   
..        ...              ...       ...       ...          ...       ...   
106 -0.423748        -0.377512 -0.314120  3.337276    -0.330528 -0.410106   
270  3.063117        -0.377512 -0.314120 -0.297273    -0.330528 -0.410106   
860 -0.423748        -0.377512 -0.314120 -0.297273    -0.330528  1.822302   
435  0.702760        -0.377512 -0.314120 -0.297273    -0.330528 -0.410106   
102 -0.423748        -0.377512 -0.314120  3.754236    -0.330528 -0.410106   

     service_dental cleaning  service_lab test  service_surgery  \
54                     False              True            False   
299                    False             False            False   
501                     True             False            False   
810                    False             False            False   
394                    False             False            False   
..                       ...               ...              ...   
106                    False             False             True   
270                    False             False            False   
860                    False             False            False   
435                    False             False            False   
102                    False             False             True   

     service_vaccination  service_x-ray  
54                 False          False  
299                False          False  
501                False          False  
810                False          False  
394                False           True  
..                   ...            ...  
106                False          False  
270                False          False  
860                False           True  
435                False          False  
102                False          False  

[744 rows x 11 columns]

In [19]:
X_test

check up  dental cleaning  lab test   surgery  vaccination     x-ray  \
828 -0.423748        -0.377512 -0.314120  4.570187    -0.330528 -0.410106   
70  -0.423748        -0.377512 -0.314120  3.158068    -0.330528 -0.410106   
630 -0.423748        -0.377512 -0.314120 -0.225214    -0.330528 -0.410106   
506  0.337885        -0.377512 -0.314120 -0.297273    -0.330528 -0.410106   
842 -0.423748        -0.377512 -0.314120  1.173311    -0.330528 -0.410106   
..        ...              ...       ...       ...          ...       ...   
2   -0.423748        -0.377512 -0.314120 -0.297273     3.153059 -0.410106   
834 -0.423748        -0.377512 -0.314120  3.599202    -0.330528 -0.410106   
735  3.335062        -0.377512 -0.314120 -0.297273    -0.330528 -0.410106   
544 -0.423748        -0.377512 -0.314120 -0.297273     1.499602 -0.410106   
5   -0.423748        -0.377512  1.578245 -0.297273    -0.330528 -0.410106   

     service_dental cleaning  service_lab test  service_surgery  \
828                    False             False             True   
70                     False             False             True   
630                    False             False             True   
506                    False             False            False   
842                    False             False             True   
..                       ...               ...              ...   
2                      False             False            False   
834                    False             False             True   
735                    False             False            False   
544                    False             False            False   
5                      False              True            False   

     service_vaccination  service_x-ray  
828                False          False  
70                 False          False  
630                False          False  
506                False          False  
842                False          False  
..                   ...            ...  
2                   True          False  
834                False          False  
735                False          False  
544                 True          False  
5                  False          False  

[187 rows x 11 columns]

### 2. Train a logistic regression model on the training data.

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [21]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression()

In [22]:
y_pred = model.predict(X_test)

### 3. Evaluate your model's performance using appropriate metrics

In [23]:
# Accuracy Score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.82


The model correctly predicts the approved and denied classes with an overall accuracy of 82%. This is fairly good but can be improved.

In [24]:
# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[54 20]
 [14 99]]


The model accurately identifies 99 out of 113 approved classes and 54 out of 74 denied classes. However, there are 20 false positives (denied classes incorrectly classified as approved) and 14 false negatives (approved classes incorrectly classified as denied).

In [25]:
# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.73      0.76        74
           1       0.83      0.88      0.85       113

    accuracy                           0.82       187
   macro avg       0.81      0.80      0.81       187
weighted avg       0.82      0.82      0.82       187



The model correctly predicted 83% of all cases classified as approved, capturing 88% of the actual approved cases. For denied cases, it achieved a precision of 79%, indicating that 79% of instances predicted as denied were accurate, while it identified 73% of all actual denied cases.

# Multi-layer Perceptron Classifier


In [26]:
from sklearn.neural_network import MLPClassifier

In [27]:
mlp = MLPClassifier()

In [28]:
mlp.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [29]:
mlp_pred = mlp.predict(X_test)

In [30]:
# Accuracy Score
accuracy = accuracy_score(y_test, mlp_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.82


In [31]:
# Confusion Matrix
conf_matrix = confusion_matrix(y_test, mlp_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[54 20]
 [14 99]]


In [32]:
# Classification Report
class_report = classification_report(y_test, mlp_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.73      0.76        74
           1       0.83      0.88      0.85       113

    accuracy                           0.82       187
   macro avg       0.81      0.80      0.81       187
weighted avg       0.82      0.82      0.82       187



### Conclusion

The model demonstrates overall good performance, accurately predicting 82% of all cases. It exhibits a stronger capability in identifying approved cases compared to denied cases, as evidenced by higher precision and recall values.